### ISSUE TITLE
Rules DSL

### ISSUE THREAD

**Issue by thelinuxlich** [Enome/knockknock#1]
Would be nice if we could add rules with a simple object syntax, like:

this.required = ko.observable();
this.max      = ko.observable();
this.regex    = ko.observable();
this.email    = ko.observable();
this.number   = ko.observable();
this.equals   = ko.observable();
this.combination = ko.observable();

this.validation = new Validation();
this.validation.addRules({
    required: new Required(),
    max: new Max(5),
    regex: new Regex( /[^/]+\d+/ ),
    email: new Email(),
    number: new Number(),
    equals: new Equals(this.number),
    combination: [new Required(), new Email()],
    validationMessages: {
        required: "Custom required message"
    }
});

**Comment by Enome** [comment]
My solution is kinda verbose and I agree there should be a better API. Your solution isn't bad so I might try and go in that direction.

**Comment by Enome** [comment]
You can now use a shorter syntax by passing a configuration object and the viewmodel to the constructor. You can find an example of this [here](http://knockknock.ep.io/example_short.html).

**Comment by thelinuxlich** [comment]
I saw your commit, very nice!
Now if only we could change the error messages on load too :)

**Comment by Enome** [comment]
That's next on the todo list. You can already change them but not in a pretty clean way.
