### ISSUE TITLE
Validation validate is incomplete

### ISSUE THREAD

**Issue by Enome** [Enome/knockknock#4]
At the moment it just runs validate on all validators in the cache. But validation should also have a isValid observable.

Something like:

   validation.validate();

```
if( validation.isValid() ){
      //Add to database.
};
```

Maybe isValid should execute validate on all validators.

**Comment by Enome** [comment]
Instead of adding isValid Validation.validate will now return true or false.

**Comment by thelinuxlich** [comment]
A global isValid would be nice for a common use case like disabling form submit button if there is any invalid field.

**Comment by Enome** [comment]
Sounds great I'll add it to features.
