### ISSUE TITLE
Sexy error handling

### ISSUE THREAD

**Issue by thelinuxlich** [Enome/knockknock#6]
Instead of typing this after every form field:
`<ul data-bind='foreach: max.errors'>`
        `<li data-bind='text: $data'></li>`
`</ul>`

For those of us, lazy programmers:
`<input type='text' data-bind='value: max, validateCss: max, showError: true' />`

Also, this would be very cool:
`<div data-bind="errorsSummary: validation"></div>`

**Comment by Enome** [comment]
Going to tackle this next. I've been looking at what a good solution is to reuse templates. Not sure if I am going to add templates to my JavaScript code but I agree that repeating all that html sucks.

**Comment by thelinuxlich** [comment]
Also, an errorTemplate: id_of_the_template would be nice for customization

**Comment by Enome** [comment]
For only the errors you can already do the following:

```
<script type='text/html' id='ErrorsTmpl'>
  <ul data-bind='foreach: $data'>
    <li data-bind='text: $data'></li>
  </ul>
</script>

<!-- ko template: { name: "ErrorsTmpl", data: expirationDays.errors } --><!-- /ko -->
```

But to really not repeat yourself it would be even better if you could just put everything in a template.

```
<script type='text/html' id='FormItem'>
  <label data-bind='text: $data.name'></label> 
  <input type='text' data-bind='value: $data, validateCss: $data' /> 
  <ul data-bind='foreach: $data.errors'> 
    <li data-bind='text: $data'></li> 
  </ul> 
</script>
```

Than you could just write:

```
<p data-bind='template: { name : "FormItem", data : observable }'></p>
<p data-bind='template: { name : "FormItem", data : observable }'></p>
<p data-bind='template: { name : "FormItem", data : observable }'></p>
```

For this to work I have to find a way so the validator knows about what name the field has and there is also a problem with the context of $data inside the foreach error loop. I asked about the context issue on the ko forum but if I don't get any response there I'll investigate it some myself.

**Comment by thelinuxlich** [comment]
ko.contextFor(element) returns an object with these template parameters like $data,$parent, etc

**Comment by thelinuxlich** [comment]
I think that dinamically adding label and form field with validation errors to a block element is too much black box.

**Comment by Enome** [comment]
Here is an example with the problem I am running into: http://jsfiddle.net/w4Shu/1/

I think but I am not sure that it is because $data is the observable's value and not the observable it self so it doesn't have the errors observableArray.

**Comment by Enome** [comment]
Well the user will have to define that template them self so it's pretty straight forward. Adding errors after an element feels very jQuery like which I am trying to avoid.

**Comment by thelinuxlich** [comment]
The text binding calls ko.unwrapObservable(value) on $data, it is the observable value.

I think the problem is that once you assign a property to dad, it behaves like an object: http://jsfiddle.net/w4Shu/16/

**Comment by Enome** [comment]
It's understandable I guess .That way people don't have to call their observable in their templates. Got an idea to solve this problem with creating my own template tag.

**Comment by Enome** [comment]
After some experimenting I wasn't really happy with the result of my own template binding. Might invest some more time into this in the future. 

I did find a way to make it less painful. I updated the [example_short.html](https://github.com/Enome/knockknock/blob/master/example_short.html) to reflect my findings. It's not totally what I want but at least it's less annoying than before.

**Comment by thelinuxlich** [comment]
I still think it's too much "magic", the errors list would be nice if it was rendered by a binding, but the whole `<label>` and `<input>`(or `<select>`,`<textarea>`,etc) is outside of the responsibility of the plugin.

**Comment by Enome** [comment]
My understanding of magic is that code is doing something behind the curtains that is complex and/or uses hacks to get there. What I am doing is just normal Knockout.js + templates. If you don't want to render the whole label and input field with templates you can just write them the long way.

**Comment by thelinuxlich** [comment]
Ok, I'll take a look at the source code when I have time and do something like this, it's a feature of jquery validation plugin and it's a nice one.

I would like to integrate your work with my project knockout.model, which always missed this validation part, what do you think?

**Comment by Enome** [comment]
You can use it it's not problem. Added a BSD license which should be pretty open if I understand it correctly. So in other words go nuts. :)
