### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by agend07** [Enome/knockknock#8]
Hi - after including knockknock I've had a problem with my application - it was constantly throwing this exception - what helped me was changing the Number validator's name to something else (KKNumber works for me) in kk.js - it seems to be a problem.

**Comment by Enome** [comment]
KnockKnock was tested with 1.3.0 beta so It's probably outdated by now. It's been a while since I used KO so I am a little out of touch with developments. I might update it in the future but for now you probably have to fork it and update it yourself.
